Zorbus\ContactBundle\Entity\Contact:
    type: mappedSuperclass
    table: zorbus_contact_contact
    repositoryClass: Zorbus\ContactBundle\Entity\ContactRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        receiver:
            type: text
            nullable: false
        cc:
            type: text
            nullable: true
        bcc:
            type: text
            nullable: true
        sender:
            type: text
            nullable: true
        title:
            type: text
            nullable: true
        subject:
            type: string
            length: 255
            nullable: true
        attachment:
            type: string
            length: 255
            nullable: true
        message:
            type: text
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update