parameters:
#    zorbus_contact.example.class: Zorbus\ContactBundle\Example

services:
#    zorbus_contact.example:
#        class: %zorbus_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
